FROM golang:1.24-alpine


WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy entire project
COPY . .

# Build API binary
RUN go build -o api ./cmd/api

EXPOSE 8080

CMD ["./api"]
